---
- name: AWX to ServiceNow Integration
  hosts: localhost
  gather_facts: false

  vars:
    snow_instance: "hcltechdemosls4.service-now.com"

    client_id: "{{ lookup('env','SN_CLIENT_ID') }}"
    client_secret: "{{ lookup('env','SN_CLIENT_SECRET') }}"

  tasks:

    - name: Generate ServiceNow Token
      uri:
        url: "https://<instance>.service-now.com/oauth_token.do"
        method: POST
        body_format: form-urlencoded
        body:
          grant_type: password
          client_id: "{{ client_id }}"
          client_secret: "{{ client_secret }}"
          username: "{{ lookup('env', 'user') }}"
          password: "{{ lookup('env', 'password') }}"
        return_content: yes
      register: token_response

    - name: Create Incident in ServiceNow
      uri:
        url: "https://{{ snow_instance }}/api/now/table/incident"
        method: POST
        headers:
          Authorization: "Bearer XFT8Ye9Ntb51guUVCbABP7bIBr4jeM"
          Content-Type: "application/json"
          Accept: "application/json"
        body_format: json
        body:
          short_description: "Incident created from AWX"
          description: "Test incident raised from AWX"
          category: "inquiry"
          impact: "2"
          urgency: "2"
        return_content: true
        status_code:
          - 200
          - 201
      register: incident_response

    - name: Display Incident Details
      debug:
        msg:
          - "Incident Number: {{ incident_response.json.result.number }}"
          - "Incident Sys ID: {{ incident_response.json.result.sys_id }}"

# - name: Fetch Open RITMs and Trigger Workflow for Each
#   hosts: localhost
#   gather_facts: no
#   vars: 
#     servicenow_instance: "https://hcltechdemosls4.service-now.com"
#   tasks:
#     - name: Get OAuth token from ServiceNow
#       uri:
#         url: "{{ servicenow_instance }}/oauth_token.do"
#         method: POST
#         use_proxy: false
#         body_format: form-urlencoded
#         body:
#           grant_type: client_credentials
#           client_id: "{{ lookup('env','SN_CLIENT_ID') }}"
#           client_secret: "{{ lookup('env','SN_CLIENT_SECRET') }}"
#           scope: useraccount
#         return_content: true
#         #status_code: 200
#       register: oauth_token_response
    
#     - name: Store access token
#       set_fact:
#         access_token: "{{ oauth_token_response.json.access_token }}"
#     - name: Get open RITMs for the catalog item
#       uri:    
#         url: "{{ servicenow_instance }}/api/now/table/sc_req_item?sysparm_query=number=RITM0013849" 
#         method: GET
#         headers:
#           Accept: "application/json"
#           Authorization: "Bearer {{ access_token }}"
#         return_content: yes
#         status_code: 200
#       register: ritm_response

#     - name: Extract RITM sys_ids and numbers
#       set_fact:
#         ritm_sys_ids: "{{ ritm_response.json.result | map(attribute='sys_id') | list }}"
#         ritm_numbers: "{{ ritm_response.json.result | map(attribute='number') | list }}"
        
#     - name: Update RITM state and work notes
#       uri:
#         url: "{{ servicenow_instance }}/api/now/table/sc_req_item/{{ ritm_sys_ids[0] }}"
#         method: PUT
#         # user: "{{ lookup('env', 'user') }}"
#         # password: "{{ lookup('env', 'password') }}"
#         # force_basic_auth: yes
#         headers:
#           #Content-Type: "application/json"
#           Accept: "application/json"
#           Authorization: "Bearer {{ access_token }}"
#         body_format: json
#         body:
#           state: "2"  # Work in Progress
#           work_notes: |
#             This request has been picked up by the VELUX Automation Team.
#             Initial analysis is underway and work has commenced.
#             Further updates will be provided as progress continues.
#         return_content: yes
#         status_code: 200
