---
- name: Prepare dynamic targets
  hosts: localhost
  gather_facts: yes
  vars:
    servicenow_instance: "https://hcltechdemosls4.service-now.com"
    assignment_group: "Nutanix%20Automation%20group"

  tasks:
    - name: Include variables
      include_vars:
        file: vars.yml

    - name: Run code compute tasks
      include_tasks: code_compute.yml

    - name: Run code compute tasks
      include_tasks: snow.yml

    # Fetch Credentials from CyberArk
    - name: Fetch CyberArk credentials
      include_role:
        name: tools_integration
        tasks_from: cyberark_integration.yml

    - name: Dynamically inject target host with CyberArk credentials
      ansible.builtin.add_host:
        name: "{{ item }}"
        groups: dynamic_cyberark_targets
        ansible_user: "{{ target_linux_user }}"
        ansible_password: "{{ target_linux_password }}"
        ansible_ssh_auth_method: password   
        filesystem_name: "{{ filesystem_name }}"
        # Privilege Escalation
        ansible_become: true
        ansible_become_method: sudo
        ansible_become_user: root
        ansible_become_password: "{{ target_linux_password }}"
      #no_log: true
      loop: "{{ target_linux_ips }}"

- name: Phase 2 - Execute Tasks on Target Linux Machine
  hosts: dynamic_cyberark_targets
  gather_facts: true
  become: true
  # vars:
  #   vg_name: vg00
  #   lv_name: lvol5
  #   lv_path: "/dev/vg00/lvol5"
  #   extend_size: "-1G"
 
  tasks:
      # Execute all validation checks before expansion
    - name: Run precheck
      include_tasks: filesystem_pre_checks.yml
      
      # include_role:
      #   name: linux_filesystem_extension
      #   tasks_from: pre_checks.yml
      
    - name: Run precheck
      include_tasks: fetch_FS_details_precheck.yml
    
