---
- name: Prepare dynamic targets
  hosts: localhost
  gather_facts: yes

  tasks:
    - name: Include variables
      include_vars:
        file: vars.yml

    - name: Run code compute tasks
      include_tasks: code_compute.yml

    # # Fetch Credentials from CyberArk
    - name: Run code compute tasks
      include_tasks: cyberark.yml
    # - name: Fetch CyberArk credentials
    #   include_role:
    #     name: tools_integration
    #     tasks_from: cyberark_integration.yml

    - name: Dynamically inject target host with CyberArk credentials
      ansible.builtin.add_host:
        name: "{{ item }}"
        groups: dynamic_cyberark_targets
        ansible_user: "{{ target_linux_user }}"
        ansible_password: "{{ target_linux_password }}"
        ansible_ssh_auth_method: password       
        # Privilege Escalation
        ansible_become: true
        ansible_become_method: sudo
        ansible_become_user: root
        ansible_become_password: "{{ target_linux_password }}"
      #no_log: true
      loop: "{{ target_linux_ips }}"

- name: Phase 2 - Execute Tasks on Target Linux Machine
  hosts: dynamic_cyberark_targets
  gather_facts: true
  become: true

  vars:
    filesystem_mount: "/tmp"

  tasks:

    - name: Get device mapped to filesystem
      shell: df {{ filesystem_mount }} --output=source | tail -1
      register: fs_device
      changed_when: false

    - name: Display filesystem device
      debug:
        msg: "Filesystem {{ filesystem_mount }} is on {{ fs_device.stdout }}"

    - name: Get VG name
      command: "lvs --noheadings -o vg_name {{ fs_device.stdout }}"
      register: vg_name
      changed_when: false

    - name: Get PV backing the VG
      command: "pvs --noheadings -o pv_name,vg_name"
      register: pv_details
      changed_when: false

    - name: Extract PV name
      set_fact:
        pv_name: >-
          {{
            (
              pv_details.stdout_lines
              | select('search', vg_name.stdout | trim)
              | list
              | first
            ).split()[0]
          }}

    - name: Display PV name
      debug:
        msg: "Physical Volume: {{ pv_name }}"

    - name: Get VG free space
      command: "vgs --noheadings -o vg_free {{ vg_name.stdout | trim }}"
      register: vg_free
      changed_when: false

    - name: Display available VG space
      debug:
        msg: "Available VG Free Space: {{ vg_free.stdout | trim }}"

    - name: Get parent disk from PV
      shell: |
        lsblk -no PKNAME {{ pv_name }} | head -1
      register: parent_disk
      changed_when: false

    - name: Set disk device
      set_fact:
        disk_device: "/dev/{{ parent_disk.stdout | trim }}"

    - name: Display disk device
      debug:
        msg: "Underlying Disk: {{ disk_device }}"

    - name: Get udev information
      shell: |
        udevadm info --query=all --name={{ disk_device }} | egrep 'ID_SERIAL=|ID_WWN='
      register: udev_info
      changed_when: false

    - name: Display udev information
      debug:
        var: udev_info.stdout_lines

    - name: Extract disk serial
      set_fact:
        disk_serial: >-
          {{
            udev_info.stdout_lines
            | select('search','ID_SERIAL=')
            | first
            | regex_replace('ID_SERIAL=','')
          }}

    - name: Display disk serial
      debug:
        msg: "Serial: {{ disk_serial }}"

    - name: Extract Nutanix Disk UUID
      set_fact:
        nutanix_disk_uuid: >-
          {{
            (disk_serial
            | regex_search('[0-9a-fA-F]{8}_[0-9a-fA-F]{4}_[0-9a-fA-F]{4}_[0-9a-fA-F]{4}_[0-9a-fA-F]{12}'))
            | replace('_', '-')
          }}

    # - name: Extract Nutanix Disk UUID
    #   set_fact:
    #     nutanix_disk_uuid: >-
    #       {{
    #         disk_serial
    #         | regex_search('[0-9a-fA-F]{8}[-][0-9a-fA-F]{4}[-][0-9a-fA-F]{4}[-][0-9a-fA-F]{4}[-][0-9a-fA-F]{12}')
    #       }}

    - name: Display Nutanix Disk UUID
      debug:
        msg: "Nutanix Disk UUID: {{ nutanix_disk_uuid | default('UUID not found') }}"

  
    - name: Get hostname
      command: hostname -s
      register: host_name
      changed_when: false

    - name: Final Summary
      debug:
        msg:
          - "Filesystem        : {{ filesystem_mount }}"
          - "LV Device         : {{ fs_device.stdout }}"
          - "VG                : {{ vg_name.stdout | trim }}"
          - "PV                : {{ pv_name }}"
          - "VG Free Space     : {{ vg_free.stdout | trim }}"
          - "Disk Device       : {{ disk_device }}"
          - "Disk Serial       : {{ disk_serial }}"
          - "Nutanix Disk UUID : {{ nutanix_disk_uuid | default('Not Found') }}"
          - "HostName          : {{ host_name.stdout }}"
