---
- name: Prepare dynamic targets
  hosts: localhost
  gather_facts: yes
  tasks:
    - name: Include required variables
      include_vars:
        file: vars.yml
      delegate_to: localhost

    - include: code_compute.yml
      delegate_to: localhost

# Fetch Credentials from CyberArk
    - include_role:
        name: roles/tools_integration
        tasks_from: cyberark_integration.yml

    - name: Dynamically inject target host with CyberArk credentials
      ansible.builtin.add_host:
        name: "{{ item }}"
        groups: dynamic_cyberark_targets
        ansible_user: "{{ target_linux_user }}"
        ansible_password: "{{ target_linux_password }}"
        ansible_ssh_auth_method: password
      no_log: true
      loop: "{{ target_linux_ips }}"


- name: Phase 2 - Execute Tasks on Target Linux Machine
  hosts: dynamic_cyberark_targets
  gather_facts: true
  tasks:
  
# Execute all validation checks before expansion
    - include_role:
        name: roles/linux_filesystem_extension
        tasks_from: precheck.yml   

# Perform filesystem expansion activities
    # - include_role:
    #     name: roles/linux_filesystem_extension
    #     tasks_from: expand.yml 


# Validate filesystem after expansion
    - include_role:
        name: roles/linux_filesystem_extension
        tasks_from: validate.yml
